from .loss import *
from .minimax import *
from .wasserstein import *
from .leastsquares import *
from .boundaryequilibrium import *
from .mutualinfo import *
from .energybased import *
from .draganpenalty import *
from .auxclassifier import *
from .historical import *
from .featurematching import *
